### ISSUE TITLE
BaseReporter.js error thrown when test is not successful

### ISSUE THREAD

**Issue by ckurban** [webdriverio-boneyard/wdio-allure-reporter#144]
```
/Users/xxxxx/dev/xxxxx/node_modules/webdriverio/build/lib/utils/BaseReporter.js:336
                        throw _iteratorError;
                        ^

TypeError: Cannot read property 'trim' of undefined
    at getTestStatus (/Users/xxxxx/dev/xxxxx/node_modules/wdio-allure-reporter/build/utils.js:31:41)
    at AllureReporter.testFail (/Users/xxxxx/dev/xxxxx/node_modules/wdio-allure-reporter/build/reporter.js:175:51)
    at emitOne (events.js:116:13)
    at AllureReporter.emit (events.js:211:7)
    at BaseReporter.handleEvent (/Users/xxxxx/dev/xxxxx/node_modules/webdriverio/build/lib/utils/BaseReporter.js:324:35)
    at Launcher.messageHandler (/Users/xxxxx/dev/xxxxx/node_modules/webdriverio/build/lib/launcher.js:688:28)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at emit (internal/child_process.js:762:12)
    at _combinedTickCallback (internal/process/next_tick.js:142:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xxxxx@0.0.1 devsk: `npm run removeReports && wdio test/config/env/dev/opCo/sk/devSK.conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the xxxxx@0.0.1 devsk script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxxxx/.npm/_logs/2018-10-09T09_13_50_399Z-debug.log
➜  xxxxx git:(develop) ✗ events.js:183
      throw er; // Unhandled 'error' event
      ^

Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
    at process.target.send (internal/child_process.js:578:16)
    at CucumberReporter.send (/Users/xxxxx/dev/xxxxx/node_modules/wdio-cucumber-framework/build/reporter.js:284:28)
    at CucumberReporter.emit (/Users/xxxxx/dev/xxxxx/node_modules/wdio-cucumber-framework/build/reporter.js:279:18)
    at CucumberReporter.handleStepResultEvent (/Users/xxxxx/dev/xxxxx/node_modules/wdio-cucumber-framework/build/reporter.js:221:18)
    at Object.hear (/Users/xxxxx/dev/xxxxx/node_modules/cucumber/lib/cucumber/listener.js:6:9)
    at iterator (/Users/xxxxx/dev/xxxxx/node_modules/cucumber/lib/cucumber/runtime/ast_tree_walker.js:176:20)
    at iterate (/Users/xxxxx/dev/xxxxx/node_modules/cucumber/lib/cucumber/util/async_for_each.js:7:7)
    at Object.asyncForEach (/Users/xxxxx/dev/xxxxx/node_modules/cucumber/lib/cucumber/util/async_for_each.js:15:3)
    at broadcastToListeners (/Users/xxxxx/dev/xxxxx/node_modules/cucumber/lib/cucumber/runtime/ast_tree_walker.js:178:23)
    at Object.broadcastEvent (/Users/xxxxx/dev/xxxxx/node_modules/cucumber/lib/cucumber/runtime/ast_tree_walker.js:186:7)
    at Object.visitStepResult (/Users/xxxxx/dev/xxxxx/node_modules/cucumber/lib/cucumber/runtime/ast_tree_walker.js:144:12)
    at /Users/xxxxx/dev/xxxxx/node_modules/cucumber/lib/cucumber/runtime/ast_tree_walker.js:264:14
    at finish (/Users/xxxxx/dev/xxxxx/node_modules/cucumber/lib/cucumber/support_code/step_definition.js:92:9)
    at process.finish (/Users/xxxxx/dev/xxxxx/node_modules/cucumber/lib/cucumber/util/run.js:13:5)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:391:26)
```

Time to time I am keep getting above written error. It seems to be related to the `wdio-allure-reporter` and I am using below written versions: 

```
  "dependencies": {
    "babel-preset-es2015": "6.3.13",
    "babel-preset-stage-0": "^6.3.13",
    "babel-register": "^6.3.13",
    "browserstack-local": "^1.3.4",
    "chai": "3.5.0",
    "chai-as-promised": "5.3.0",
    "commander": "^2.15.1",
    "cucumber": "^0.10.4",
    "deepmerge": "^2.1.1",
    "fibers": "^2.0.2",
    "googleapis": "^30.0.0",
    "interval-promise": "^1.2.0",
    "jsonpath": "^1.0.0",
    "moment": "^2.22.2",
    "node-html-parser": "^1.1.10",
    "node-uuid": "^1.4.7",
    "request": "^2.87.0",
    "request-promise": "^4.2.2",
    "wait-until": "0.0.2",
    "wdio-cucumber-framework": "0.1.0",
    "wdio-dot-reporter": "0.0.5",
    "wdio-sauce-service": "^0.4.10",
    "wdio-screenshots-cleanup-service": "0.0.7",
    "webdriverio": "4.12.0"
  },
  "devDependencies": {
    "allure-commandline": "^1.5.0",
    "base64url": "^3.0.0",
    "eslint": "^5.6.0",
    "eslint-plugin-react": "^3.16.1",
    "selenium-standalone": "^6.14.0",
    "wdio-allure-reporter": "^0.6.3",
    "wdio-browserstack-service": "^0.1.16",
    "wdio-json-reporter": "^0.3.1",
    "wdio-junit-reporter": "0.0.2",
    "wdio-phantomjs-service": "^0.2.2",
    "wdio-selenium-standalone-service": "0.0.10",
    "wdio-spec-reporter": "^0.1.4",
    "winston": "^2.4.2"
  }
```

**Comment by BorisOsipov** [comment]
@ckurban is it stable?
Also
`"wdio-cucumber-framework": "0.1.0"` can you update to at least `1.1.1` ?

**Comment by ckurban** [comment]
@BorisOsipov it is not stable. Upgrading might be tricky as it might/will change the structure of the Step Definitions which means I would need to apply major refactoring on all my scenarios but i will have it a go and see whats the outcome.

**Comment by BorisOsipov** [comment]
@ckurban Any updates on this? have you fixed problem?

**Comment by ckurban** [comment]
Hey @BorisOsipov I see this now all the time so yes it is stable now :) Can we re-open the ticket ?

**Comment by BorisOsipov** [comment]
I don't think it makes sense. It won't be fixed anyway. Solution for you is update to at least 1.x `wdio-cucumber-framework` version
