### ISSUE TITLE
Error: channel closed

### ISSUE THREAD

**Issue by matotej** [webdriverio-boneyard/wdio-allure-reporter#36]
I get these two errors repeated n-times immediately after I add allure to the wdio conf like this:
```yaml
reporters: ['dot','spec','allure'],
reporterOptions: {
    allure: {
        outputDir: 'allure-results'
    }
},
```

```console
Error: channel closed
    at process.target.send (internal/child_process.js:548:16)
    at /home/matej/Documents/Testing/webdriverio/node_modules/webdriverio/build/lib/runner.js:513:25
    at execHook (/home/matej/Documents/Testing/webdriverio/node_modules/wdio-sync/build/index.js:259:35)
Error: channel closed
    at process.target.send (internal/child_process.js:548:16)
    at /home/matej/Documents/Testing/webdriverio/node_modules/webdriverio/build/lib/runner.js:525:25
    at execHook (/home/matej/Documents/Testing/webdriverio/node_modules/wdio-sync/build/index.js:259:35)
```

And at the end:
```console
/home/matej/Documents/Testing/webdriverio/node_modules/q/q.js:155
                throw e;
                ^

Error: channel closed
    at process.target.send (internal/child_process.js:548:16)
    at EventEmitter.<anonymous> (/home/matej/Documents/Testing/webdriverio/node_modules/webdriverio/build/lib/runner.js:177:45)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at Object.prototype.(anonymous function) [as emit] (/home/matej/Documents/Testing/webdriverio/node_modules/webdriverio/build/lib/webdriverio.js:745:40)
    at /home/matej/Documents/Testing/webdriverio/node_modules/webdriverio/build/lib/multibrowser.js:163:23
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

I did a fresh install of webdriverio and install the allure during the wdio config procedure. I use mocha framework for my test and they pass if I don't use the allure reporter. I use Selenium 3.0.1.

My package.json
```yaml
"devDependencies": {
    "wdio-allure-reporter": "^0.1.2",
    "wdio-dot-reporter": "0.0.7",
    "wdio-mocha-framework": "^0.5.8",
    "wdio-spec-reporter": "0.0.5",
    "webdriverio": "^4.6.2"
  },
```

I use Ubuntu 16.04. Any help would be greatly appreciated.
Thank you!

**Comment by swetashahi-brightplan** [comment]
@matotej: Any update on this issue? Did you find a workaround?

**Comment by mkj28** [comment]
Ping @matotej  again :) any luck working around it? We are hitting the same/similar issue.

**Comment by BorisOsipov** [comment]
@mkj28 Can you share with us simple project when issue occurs?

**Comment by BorisOsipov** [comment]
Close due inactive.
