### ISSUE TITLE
Long Session not generating report

### ISSUE THREAD

**Issue by anjana-sundaram** [webdriverio-boneyard/wdio-allure-reporter#47]
Hi!

I am using wdio 4.8.0 + Mocha 0.5.9 + wdio-allure-reporter 0.1.2 

When my test case runs more than a minute in my case its an E-commerce application i am testing E2E. This creates more than 1000 attachment JSON files and at the end it fails with following error without creating XML file.

```
> node node_modules/webdriverio/bin/wdio conf/wdio.conf.js --mochaOpts.grep=@Current  --suite  "smoketest"


C:\works\project\magento\automate\functional\node_modules\webdriverio\build\lib\utils\BaseReporter.js:336
                        throw _iteratorError;
                        ^

RangeError: Maximum call stack size exceeded
    at parseObjectOrMapEntry (C:\works\project\magento\automate\functional\node_modules\js2xmlparser\lib\main.js:92:31)
    at parseObjectOrMap (C:\works\project\magento\automate\functional\node_modules\js2xmlparser\lib\main.js:152:13)
    at parseValue (C:\works\project\magento\automate\functional\node_modules\js2xmlparser\lib\main.js:220:9)
    at C:\works\project\magento\automate\functional\node_modules\js2xmlparser\lib\main.js:192:9
    at Array.forEach (native)
    at parseArrayOrSet (C:\works\project\magento\automate\functional\node_modules\js2xmlparser\lib\main.js:187:16)
    at parseValue (C:\works\project\magento\automate\functional\node_modules\js2xmlparser\lib\main.js:224:9)
    at parseObjectOrMapEntry (C:\works\project\magento\automate\functional\node_modules\js2xmlparser\lib\main.js:132:5)
    at parseObjectOrMap (C:\works\project\magento\automate\functional\node_modules\js2xmlparser\lib\main.js:152:13)
    at parseValue (C:\works\project\magento\automate\functional\node_modules\js2xmlparser\lib\main.js:220:9)
```

I am not sure whether i could suppress the JSON creation (if i am not interested in detailed steps).

**Comment by just-boris** [comment]
Seems like you create a circular references in your data structure. I will take a look.

**Comment by anjana-sundaram** [comment]
@just-boris i checked my code there is no circular dependency. Did you find anything?

**Comment by BorisOsipov** [comment]
Close due inactive.
